/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figuras;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Angel
 */
public class inicio extends javax.swing.JFrame {
int lineax=0;
int lineay=0;
int linex2=0;
int linea3=0;
double esca=1.0;
double esca1=1.0;
int rotacion=0;
    /**
     * Creates new form inicio
     */
    public inicio() {
this.setContentPane(new Graficos());

        initComponents();
this.setLocationRelativeTo(null);

jSpinner1.addChangeListener(new ChangeListener(){
@Override
public void stateChanged(ChangeEvent e){
int exponente=(int)jSpinner1.getValue();
esca=Math.pow(2, exponente);
repaint();
}
});
jSpinner2.addChangeListener(new ChangeListener(){
@Override
public void stateChanged(ChangeEvent e){
int exponente=(int)jSpinner2.getValue();
esca1=Math.pow(2, exponente);
repaint();
}
});
jSpinner3.addChangeListener(new ChangeListener(){
@Override
public void stateChanged(ChangeEvent e){

rotacion=(int)jSpinner3.getValue();
repaint();
}

});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtlinea = new javax.swing.JTextField();
        txtlinea1 = new javax.swing.JTextField();
        txtlinea2 = new javax.swing.JTextField();
        txtlinea3 = new javax.swing.JTextField();
        btnlinea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtlinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 103, -1));
        getContentPane().add(txtlinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 102, -1));
        getContentPane().add(txtlinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 108, -1));
        getContentPane().add(txtlinea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 112, -1));

        btnlinea.setText("Crear");
        btnlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlineaActionPerformed(evt);
            }
        });
        getContentPane().add(btnlinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Linea");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 480, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 608, 90, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 90, -1));

        jLabel2.setText("Escalado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 640, -1, -1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, -360, 360, 1));
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 90, -1));

        jLabel3.setText("Rotacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 180, 100));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 200, 70));

        jLabel6.setText("Punto A");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        jLabel7.setText("X");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jLabel8.setText("Y");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        jLabel9.setText("Punto B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        jLabel10.setText("X");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jLabel11.setText("Y");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 80, 150));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlineaActionPerformed
        // TODO add your handling code here:
lineax=Integer.parseInt(txtlinea.getText());
lineay=Integer.parseInt(txtlinea1.getText());
linex2=Integer.parseInt(txtlinea2.getText());
linea3=Integer.parseInt(txtlinea3.getText());
repaint();
    }//GEN-LAST:event_btnlineaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
menu o=new menu();
o.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

public class Graficos extends JPanel{
@Override
  public void paint(Graphics g){
super.paint(g);
Graphics2D g2d=(Graphics2D)g;
g2d.scale(esca, esca1);
g2d.rotate(Math.toRadians(rotacion));

g2d.setColor(Color.RED);
g2d.drawLine(lineax, lineay, linex2, linea3);
}

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlinea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField txtlinea;
    private javax.swing.JTextField txtlinea1;
    private javax.swing.JTextField txtlinea2;
    private javax.swing.JTextField txtlinea3;
    // End of variables declaration//GEN-END:variables

/*
public void paint(Graphics g){
super.paint(g);
Graphics2D g2d=(Graphics2D)g;
g2d.translate(x, y);
g2d.scale(escalado, escalado1);
g2d.rotate(Math.toRadians(rotacion));

g2d.fillRect(0, 0, ancho, alto);
}
*/
}
